### ISSUE TITLE
Local file caching

### ISSUE THREAD

**Issue by simonschaufi** [Richardds/ECB-API#1]
Hello!
Thank you very much for implementing this API! I use it and would like to have some small improvement:
Since the xml file is currently fetched on **every** request, I would like to store it for some hours until I will fetch it again.

As an inspiration, you could do the same like https://github.com/simplepie/simplepie. The file cache would be enough for me right now. This is how they implemented it:

https://github.com/simplepie/simplepie/blob/master/tests/CacheTest.php#L95-L100

PS: Please also tag the current state as I can only require dev-master via composer. Thanx!

**Comment by Richardds** [comment]
Hey!
I added simple caching and tagged commit as version **1.0.1** :)

**Comment by simonschaufi** [comment]
Thank you very much! I will test it this week. But I'm not sure if the .idea files should be in git repo

**Comment by simonschaufi** [comment]
I have tested the new version and need to say, it's only half done.
There is no way to access the rates via the ECBConverter, I can only convert it but I want to do that myself as I also need to store the rate in my database but there is no way to access it.

So I used ECB::getExchangeReferences which is not cached yet. I though that you have actually cached exactly this method since this fetches the data.

Please also remove the .idea folder from git.

**Comment by Richardds** [comment]
See **example_02.php** I hope it is okay now. :)

**Comment by simonschaufi** [comment]
Thank you very much! It is exactly how I wanted it to be! 😍

**Comment by simonschaufi** [comment]
one more thing you could do is to update the documentation.
