### ISSUE TITLE
Problem with float amount

### ISSUE THREAD

**Issue by enriquealcaraz** [Richardds/ECB-API#11]
I am testing the library and I cannot convert quantities with decimals. For example 150.2 and I can't convert amounts like 0.69 to euros either.

Can you tell me how to do these conversions?

**Comment by Richardds** [comment]
Hello Enrique, could you please provide a code example? Thank You

**Comment by enriquealcaraz** [comment]
```php
use Richardds\ECBAPI\ECBConverter;

$converter = new ECBConverter();

echo $converter->toEuro(0.89, 'USD', 3);
```

**Comment by enriquealcaraz** [comment]
any news?

**Comment by sellrock-de** [comment]
Have same problem :)
