### ISSUE TITLE
Is there a way to change the base currency from EUR to something else?

### ISSUE THREAD

**Issue by yonkov** [Richardds/ECB-API#17]
I wonder if there is a way to change the base currency from EUR to lets say BGN, e.g. USD -> BGN; CZK ->BGN, etc. Thank you!

**Comment by Richardds** [comment]
Hi Atanas,
The official ECB rates only provide a rate between the euro and other world currencies.

The actual ECB data used in this library is [here](https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml).
