### ISSUE TITLE
URL change

### ISSUE THREAD

**Issue by mike22** [Richardds/ECB-API#2]
Hi, first of all, thank you for the API. I run into one issue today. (worked perfectly before)

URL to XML with daily rates should be changed to https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

Old URL with http returns status 301 and script doesnt work...

**Comment by Richardds** [comment]
Hi, i checked URL and it is same. Could you please send me file/line or just create pull request? :)

**Comment by mike22** [comment]
Hi, pull request added https://github.com/Richardds/ECB-API/pull/3

**Comment by mkarnicki** [comment]
Hi. Due to poor error monitoring (and test assuming ECBConverter could throw), I realized I failed to issue invoices for the whole previous month. Why has this issue been closed? I can confirm the problem.

```
Richardds\\ECBAPI\\ECBException(code: 1): Failed to download data from ECB <= HTTP_CODE != 200
```

Surely that's the http->https redirect.

**Comment by mkarnicki** [comment]
If this helps anyone, this url allows you to fetch historical data, which (at least currently) ECBConverter doesn't support.

https://sdw-wsrest.ecb.europa.eu/service/data/EXR/D.%s.EUR.SP00.A?detail=dataonly&startPeriod=%s&endPeriod=%s&dimensionAtObservation=AllDimensions

First %s is USD in my case, second and third %s should be the date you're interested in formatted as YYYY-MM-DD.

**Comment by Richardds** [comment]
URL change merged.
